// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name authorizer
 */


/* @ngInject */

(function() {
    module.exports = function(localStorageService) {
        var factory = {};

        factory.api_url = "{@= LET.api_url @}";

        factory.isAuthenticated = function () {
            return !!localStorageService.get('session.token'); // && localStorageService.get('session.user').admin;
        };

        factory.setHeadersAuthorization = function (request) {
            if (factory.isAuthenticated()) {
                request.headers = request.headers || {};
                request.headers.Authorization = 'Bearer ' + localStorageService.get('session.token');
            }
            return request;
        };

        return factory;
    };

}).call(this);


