// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name authenticator
 */


/* @ngInject */

(function() {
    module.exports = function($http, localStorageService, $location) {
        var factory = {};

        factory.api_url = "{@= LET.api_url @}" + "/admin";

        factory.authenticate = function (credentials) {
            $http.defaults.headers.common.Authorization = 'Basic ' + window.btoa(credentials.username + ':' + credentials.password);
            return $http.post(factory.api_url + '/token', credentials)
                .success(function(res){
                    $http.get(factory.api_url + '/users')
                        .success(function(user){
                            factory.setUser(user);
                        });
                });
        };

        factory.invalidate = function () {
            var config = {};
            config.data = {
                token: factory.getToken()
            };
            return $http.delete(factory.api_url + '/token/' + factory.getToken(), config)
                .success(function(){
                    localStorageService.clear();
                    $location.path('/login');
                })
                .error(function(res){
                    console.log(res);
                });
        };

        factory.setToken = function(token) {
            localStorageService.set('session.token', token);
        };

        factory.setUser = function(user){
            localStorageService.set('session.user', user);
        };

        factory.getToken = function() {
            return localStorageService.get('session.token');
        };

        factory.getUser = function() {
            return localStorageService.get('session.user');
        };

        return factory;
    };

}).call(this);

