// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name issueservice
 */


/* @ngInject */

(function() {
    module.exports = function($http, Upload) {
        var factory = {};

        factory.api_url = "{@= LET.api_url @}" + "/admin";

        factory.getAll = function (filter) {
            if(filter === undefined) {
                filter = '';
            }
            return $http.get(factory.api_url + '/issues' + filter);
        };

        factory.get = function (id) {
            return $http.get(factory.api_url + '/issues/' + id);
        };

        factory.trash = function () {
            return $http.get(factory.api_url + '/issues/trash');
        };

        factory.create = function () {
            return $http.post(factory.api_url + '/issues/', { auto: true });
        };

        factory.activate = function (issue) {
            return $http.post(factory.api_url + '/issues/' + issue._id + '/activate', { issue: issue })
        };

        factory.admin = function (issue) {
            return $http.post(factory.api_url + '/issues/' + issue._id + '/admin', { issue: issue })
        };

        factory.delete = function (issue) {
            return $http.delete(factory.api_url + '/issues/' + issue._id);
        };

        factory.edit = function (issue) {
            return $http.post(factory.api_url + '/issues/' + issue._id, { issue: issue });
        };

        factory.editCover = function (issueId, pageId) {
            return $http.post(factory.api_url + '/issues/' + issueId + '/cover/' + pageId, { id: issueId, pageid: pageId });
        };

        factory.upload = function(issue, file) {
            return Upload.upload({
                url: factory.api_url + '/issues/' + issue._id + '/upload',
                fields: {'title': issue.title, 'number': issue.number},
                file: file
            })
        };

        factory.removePage = function (pageId) {
            return $http.delete(factory.api_url + '/issues/page/' + pageId);
        };

        return factory;
    };

}).call(this);


