// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name authenticator
 */


/* @ngInject */

(function() {
    module.exports = function($window) {

        return {
            set: function(key, value) {
                $window.localStorage[key] = value;
            },
            get: function(key, defaultValue) {
                return $window.localStorage[key] || defaultValue;
            },
            setObject: function(key, value) {
                $window.localStorage[key] = JSON.stringify(value);
            },
            getObject: function(key) {
                return JSON.parse($window.localStorage[key] || '{}');
            },
            clear: function() {
                $window.localStorage.clear();
            },
            removeItem: function(key) {
                $window.localStorage.removeItem(key);
            }
        }
    };

}).call(this);

