// Generated by CoffeeScript 1.8.0

/**
@author
@description
@name menuFactory
 */


/* @ngInject */

(function() {
    module.exports = function($rootScope, $location) {
        var factory;

        factory = {
            currentPage: null,
            sections: [
                {
                    type: 'link',
                    name: 'Dashboard',
                    key: 'dashboard',
                    url: '/',
                    public: false
                },
                {
                    type: 'link',
                    name: 'Login',
                    key: 'login',
                    url: '/login',
                    public: true
                },
                {
                    type: 'link',
                    name: 'Revistas',
                    key: 'issues',
                    url: '/issues',
                    public: false
                },
                {
                    type: 'link',
                    name: 'Usuarios',
                    key: 'users',
                    url: '/users',
                    public: false
                },
                {
                    type: 'link',
                    name: 'Promociones',
                    key: 'promotions',
                    url: '/promotions',
                    public: false
                },
                {
                    type: 'link',
                    key: 'logout',
                    name: 'Logout',
                    url: '/logout',
                    public: false
                }
            ]
        };

        factory.getCurrentPage = function() {
            return factory.currentPage;
        }


        factory.selectPage = function(page) {
          factory.currentPage = page;
        };

        factory.isPageSelected = function(page) {
          return factory.currentPage === page;
        };

        function onLocationChange() {
            var path = $location.path();

            var matchPage = function(page) {
              if (path === page.url) {
                  factory.selectPage(page);
              }
            };

            factory.sections.forEach(function(page) {
                if(page) {
                    matchPage(page);
                }
            });
        }

        $rootScope.$on('$locationChangeSuccess', onLocationChange);

        return factory;
  };

}).call(this);
