// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name promotionService
 */


/* @ngInject */

(function() {
    module.exports = function($http) {
        var factory = {};

        factory.api_url = "{@= LET.api_url @}";

        factory.getAll = function () {
            return $http.get(factory.api_url + '/promotions');
        };

        factory.get = function (id) {
            return $http.get(factory.api_url + '/promotions/' + id);
        };

        return factory;
    };

}).call(this);


