// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name userService
 */


/* @ngInject */

(function() {
    module.exports = function($http) {
        var factory = {};

        factory.api_url = "{@= LET.api_url @}" + "/admin";

        factory.getAll = function () {
            return $http.get(factory.api_url + '/users');
        };

        factory.get = function (id) {
            return $http.get(factory.api_url + '/users/' + id);
        };

        factory.create = function () {
            return $http.post(factory.api_url + '/users/', { auto: true });
        };

        factory.activate = function (user) {
            return $http.post(factory.api_url + '/users/' + user._id + '/activate', { user: user })
        };

        factory.admin = function (user) {
            return $http.post(factory.api_url + '/users/' + user._id + '/admin', { user: user })
        };

        factory.delete = function (user) {
            return $http.delete(factory.api_url + '/users/' + user._id);
        };

        factory.edit = function (user) {
            return $http.post(factory.api_url + '/users/' + user._id, { user: user });
        };

        return factory;
    };

}).call(this);


