// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name voucherService
 */


/* @ngInject */

(function() {
    module.exports = function($http) {
        var factory = {};

        factory.api_url = "{@= LET.api_url @}";

        factory.getAll = function () {
            return $http.get(factory.api_url + '/vouchers');
        };

        factory.get = function (id) {
            return $http.get(factory.api_url + '/vouchers/' + id);
        };

        factory.add = function (voucher) {
            return $http.post(factory.api_url + '/vouchers/', { voucher: voucher });
        };

        factory.active = function (voucher) {
            return $http.post(factory.api_url + '/vouchers/' + voucher._id + '/activate', { voucher: voucher })
        };

        return factory;
    };

}).call(this);


