// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  describe("Directive: bd-header", function() {
    beforeEach(angular.mock.module("{@= app_name @}"));
    beforeEach(inject(function(_$compile_, _$rootScope_) {
      var $compile, $rootScope;
      $compile = _$compile_;
      $rootScope = _$rootScope_;
    }));
    it("Replaces the element with the appropriate content", function() {
      var element;
      element = $compile("<bd-header></bd-header>")($rootScope);
      $rootScope.$digest();
      expect(element.html()).toContain("lidless, wreathed in flame, 2 times");
    });
  });

}).call(this);
