// Generated by CoffeeScript 1.7.1

/* @ngInject */
module.exports = function($rootScope, $mdSidenav, $timeout, menuService, authorizerService, authenticatorService) {

    $rootScope.site = {};
    $rootScope.session = {};

    $rootScope.site.closeMenu = closeMenu;
    $rootScope.site.openMenu = openMenu;
    $rootScope.site.path = path;
    $rootScope.site.goHome = goHome;
    $rootScope.site.openPage = openPage;
    $rootScope.site.isSelected = isSelected;
    $rootScope.site.selectPage = selectPage;
    $rootScope.site.getCurrentPage = menuService.getCurrentPage;

    $rootScope.session.isAuthenticated = authorizerService.isAuthenticated;
    $rootScope.session.invalidate = authenticatorService.invalidate;

    function path() {
        return $location.path();
    }

    function goHome() {
        $location.path( '/' );
    }

    function openPage() {
        $rootScope.site.closeMenu('left');
    }

    function isSelected(page) {
        return menuService.isPageSelected(page);
    }

    function selectPage(page) {
        return menuService.selectPage(page);
    }

    function closeMenu(id) {
        $timeout(function() { $mdSidenav(id).close(); });
    }

    function openMenu(id) {
        $timeout(function() { $mdSidenav(id).open(); });
    }


};
