// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name bd-footer
 */

(function() {
    "use strict";

    /* @ngInject */
    module.exports = function() {
        return {
            restrict: "E",
            replace: true,
            templateUrl: "templates/directives/bd-footer.html"
        };
    };

}).call(this);
