// Generated by CoffeeScript 1.8.0

/**
@author
@description
@name bd-header
 */

(function() {
  "use strict";

  /* @ngInject */
  module.exports = function() {
    return {
      restrict: "E",
      replace: true,
      templateUrl: "templates/directives/bd-header.html"
    };
  };

}).call(this);
