// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name bd-sidebar
 */

(function() {
    "use strict";

    /* @ngInject */
    module.exports = function() {
        return {
            restrict: "E",
            replace: true,
            templateUrl: "templates/directives/bd-sidebar.html",
            controller: function($scope, menuService){
                $scope.sections = menuService.sections;
            }
        };
    };

}).call(this);
