// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name check-username
 */

(function() {
    "use strict";

    /* @ngInject */
    module.exports = function(userService) {
        return {
            restrict: 'A',
            require: 'ngModel',
            link: function (scope, element, attrs, ngModel) {
                element.bind('blur', function (e) {
                    ngModel.$loading = true;

                    userService.check(element.val()).success(function(user) {
                        console.log(user);
                        ngModel.$loading = false;
                        ngModel.$setValidity('uniqueUsername', !user.exist);
                    });
                });
            }
        };
    };

}).call(this);

