// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name compare-to
 */

(function() {
    "use strict";

    /* @ngInject */
    module.exports = function() {
        return {
            require: "ngModel",
            scope: {
                otherModelValue: "=compareTo"
            },
            link: function(scope, element, attributes, ngModel) {

                ngModel.$validators.compareTo = function(modelValue) {
                    return modelValue == scope.otherModelValue;
                };

                scope.$watch("otherModelValue", function() {
                    ngModel.$validate();
                });
            }
        };
    };

}).call(this);
