// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name menu-link
 */

(function() {
    "use strict";

    /* @ngInject */
    module.exports = function() {
        return {
            scope: {
                section: '='
            },
            templateUrl: 'templates/directives/menu-link.html',
            controller: function($scope, $rootScope){
                $scope.isSelected = function() {
                    return $rootScope.site.isSelected($scope.section);
                };

                $scope.checkAction = function() {
                    if($scope.section.key === 'logout') {
                        $rootScope.session.invalidate();
                        $scope.focusSection();
                    } else {
                        $scope.focusSection();
                    }
                };

                $scope.focusSection = function() {
                    $rootScope.site.closeMenu('left');
                };
            }
        };
    };

}).call(this);
