// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name popup-menu
 */

(function() {
    "use strict";

    /* @ngInject */
    module.exports = function() {
        return {
            scope: {
                actionList: '=',
                item: '='
            },
            templateUrl: 'templates/directives/popup-menu.html',
            controller: function($scope){
                $scope.visible = false;

                $scope.show = function() {
                    $scope.visible = true;
                };

                $scope.hide = function() {
                    $scope.visible = false;
                };

                $scope.toggle = function() {
                    $scope.visible = !$scope.visible;
                }
            }
        };
    };

}).call(this);

