// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name createController
 */


/* @ngInject */

(function() {
    module.exports = function($scope, $routeParams, $mdToast, $mdBottomSheet, $mdDialog, $location, issueService) {
        
        $scope.issue = {};

        $scope.init = function() {
            if($routeParams.id) {
                issueService.get($routeParams.id)
                    .success(function(res){
                        $scope.issue = res.issue;
                        if($scope.issue.number) {
                            $scope.issue.number = parseInt($scope.issue.number, 10);
                        }
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                    });

            } else {
                issueService.create()
                    .success(function(res){
                        $scope.issue = res.issue;
                    })
                    .error(function(){
                        $location.path('/issues');
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error al crear la revista. Intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                    });
            }
            console.log($scope.issue);
        };

        $scope.$watch('files', function () {
            if($scope.files && $scope.files.length > 0)
                $scope.upload($scope.files);
        });

        $scope.upload = function (files) {
            if (files && files.length) {
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    issueService.upload($scope.issue, file)
                        .progress(function (evt) {
                            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                            //console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                        }).success(function (data, status, headers, config) {
                            //console.log('file ' + config.file.name + ' uploaded. Response: ' + data);
                            $mdToast.show({
                                controller: function($scope, $mdToast) {
                                    $scope.closeToast = function() {
                                        $mdToast.hide();
                                    }
                                },
                                template: '<md-toast> <span flex>La imagén '+ config.file.name +' se ha guardado exitosamente.</span><md-button ng-click="closeToast()">Close</md-button></md-toast>',
                                hideDelay: 7000,
                                position: 'top right'
                            });
                            $scope.reload();
                        });
                }
            }
        };

        $scope.cancel = function($event) {
            $event.preventDefault();
            //delete only when creation canceled
            if(!$routeParams.id) {
                issueService.delete($scope.issue)
                    .success(function(){
                        $location.path('/issues');
                    });
            } else {
                $location.path('/issues');
            }

        };

        $scope.reload = function() {
            issueService.get($scope.issue._id)
                .success(function(res){
                    $scope.issue = res.issue;
                    if($scope.issue.number) {
                        $scope.issue.number = parseInt($scope.issue.number, 10);
                    }
                })
                .error(function(){
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                });
        };

        $scope.showPages = function() {
            var pagesContainer = angular.element(document.querySelector('.issue-edit-container .pages'));
            if(pagesContainer.hasClass('hide')){
                pagesContainer.removeClass('hide');
            } else {
                pagesContainer.addClass('hide');
            }
        };

        $scope.pageIcon = function(path, file) {
          return path + file;
        };

        $scope.init();

    };

}).call(this);

