// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name createController
 */


/* @ngInject */

(function() {
    module.exports = function($scope, $routeParams, $mdToast, $mdBottomSheet, $mdDialog, $location, issueService, $timeout) {

        $scope.issue = {};

        $scope.loading = true;
        $scope.error = false;

        $scope.init = function() {
            if($routeParams.id) {
                issueService.get($routeParams.id)
                    .success(function(res){
                        $scope.issue = res.issue;
                        if($scope.issue.number) {
                            $scope.issue.number = parseInt($scope.issue.number, 10);
                        }
                        $scope.loading = false;
                        //console.log($scope.issue);
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.loading = false;
                        $scope.error = true;
                    });

            } else {
                issueService.create()
                    .success(function(res){
                        $scope.issue = res.issue;
                        $scope.loading = false;
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error al crear la revista. Intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.loading = false;
                        $scope.error = true;
                    });
            }
        };

        $scope.$watch('files', function () {
            if($scope.files && $scope.files.length > 0)
                $scope.upload($scope.files);
        });

        //autosave
        var debounceSaveUpdates = function(newVal, oldVal) {
            if (newVal != oldVal) {
                console.log(newVal);
                timeout = $timeout($scope.save, 1000);  // 1000 = 1 second
            }
        };
        $scope.$watch($scope.issue.title, debounceSaveUpdates);
        $scope.$watch($scope.issue.number, debounceSaveUpdates);

        $scope.upload = function (files) {
            if (files && files.length) {
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    issueService.upload($scope.issue, file)
                        .progress(function (evt) {
                            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                            $scope.loading = true;
                            //console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                        }).success(function (data, status, headers, config) {
                            //console.log('file ' + config.file.name + ' uploaded. Response: ' + data);
                            $mdToast.show({
                                controller: function($scope, $mdToast) {
                                    $scope.closeToast = function() {
                                        $mdToast.hide();
                                    }
                                },
                                template: '<md-toast> <span flex>La imagén '+ config.file.name +' se ha guardado exitosamente.</span><md-button ng-click="closeToast()">Close</md-button></md-toast>',
                                hideDelay: 7000,
                                position: 'top right'
                            });
                            $scope.reload();
                            $scope.loading = false;
                        });
                }
            }
        };

        $scope.cancel = function($event) {
            $event.preventDefault();
            //delete only when creation canceled
            if(!$routeParams.id) {
                issueService.delete($scope.issue)
                    .success(function(){
                        $location.path('/issues');
                    });
            } else {
                $location.path('/issues');
            }

        };

        $scope.save = function(redirect) {
            $scope.loading = true;
            issueService.edit($scope.issue)
                .success(function(res){
                    if(res.issue){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('La revista se guardo exitosamente.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.loading = false;
                        if(redirect)  {
                            $location.path('/issues');
                        }
                    }
                })
                .error(function(){
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                    $scope.loading = false;
                });
        };

        $scope.reload = function() {
            issueService.get($scope.issue._id)
                .success(function(res){
                    $scope.issue = res.issue;
                    if($scope.issue.number) {
                        $scope.issue.number = parseInt($scope.issue.number, 10);
                    }
                })
                .error(function(){
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                });
        };

        $scope.showPages = function() {
            var pagesContainer = angular.element(document.querySelector('.issue-edit-container .pages'));
            if(pagesContainer.hasClass('hide')){
                pagesContainer.removeClass('hide');
            } else {
                pagesContainer.addClass('hide');
            }
        };

        $scope.getImageUrl = function(page) {
          return page.fullsize;
        };

        $scope.getThumbUrl = function(page) {
            return page.thumb;
        };

        $scope.removePage = function($event, page) {
            var confirm = $mdDialog.confirm()
                .title('Realmente deseas eliminar la pagina: ' + page.file_name + '?')
                .content('Esta acción no puede deshacerse.')
                .ariaLabel('Eliminar pagina')
                .ok('Eliminar')
                .cancel('Cancelar')
                .targetEvent($event);
            $mdDialog.show(confirm).then(function() {
                issueService.removePage(page._id)
                    .success(function(res){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Se ha eliminado la pagina exitosamente.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.init();
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                    });
            }, function() {
                $mdToast.show(
                    $mdToast.simple()
                        .content('La eliminacion ha sido cancelada.')
                        .position('top right')
                        .hideDelay(3000)
                );
            });
        };

        $scope.editCover = function(issueId, pageId) {
            issueService.editCover(issueId, pageId)
                .success(function(res){
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Se ha establecido la portada exitosamente.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                    $scope.init();
                })
                .error(function(){
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                });
        };

        $scope.init();

    };

}).call(this);

