// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name trashController
 */


/* @ngInject */

(function() {
    module.exports = function($scope, $mdBottomSheet, $location, $mdToast, $mdDialog, issueService) {
        $scope.issues = [];

        $scope.loading = true;
        $scope.error = false;

        $scope.init = function(){
            $scope.getAll();
        };

        $scope.getAll = function() {
            issueService.trash()
                .success(function(res){
                    console.log(res.issues);
                    $scope.issues = res.issues;
                    $scope.loading = false;
                    $scope.error = false;
                })
                .error(function(res){
                    console.log(res);
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                    $scope.error = true;
                    $scope.loading = false;
                });
        };

        $scope.delete = function($event, issue) {
            var confirm = $mdDialog.confirm()
                .title('Realmente deseas eliminar la revista: ' + issue.title + '?')
                .content('Esta acción no puede deshacerse.')
                .ariaLabel('Eliminar revista')
                .ok('Eliminar')
                .cancel('Cancelar')
                .targetEvent($event);
            $mdDialog.show(confirm).then(function() {
                issueService.delete(issue)
                    .success(function(res){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Se ha eliminado la revista exitosamente.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.init();
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                    });
            }, function() {
                $mdToast.show(
                    $mdToast.simple()
                        .content('La eliminacion ha sido cancelada.')
                        .position('top right')
                        .hideDelay(3000)
                );
            });
        };

        $scope.showActions = function($event, issue) {
            var selfScope = $scope;

            $mdBottomSheet.show({
                templateUrl: 'templates/issues/bottom-sheet-action-trash.html',
                controller: function($scope){
                    $scope.issue = issue;

                    $scope.delete = function() {
                        selfScope.delete($event, issue);
                        $mdBottomSheet.hide();
                    };

                    $scope.restore = function() {
                        $scope.issue.status = 'restored';
                        $scope.active = true;
                        issueService.edit($scope.issue)
                            .success(function(res){
                                if(res.issue){
                                    $mdToast.show(
                                        $mdToast.simple()
                                            .content('La revista se restauro exitosamente.')
                                            .position('top right')
                                            .hideDelay(3000)
                                    );
                                    selfScope.init();
                                }
                            })
                            .error(function(){
                                $mdToast.show(
                                    $mdToast.simple()
                                        .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                        .position('top right')
                                        .hideDelay(3000)
                                );
                            });
                        $mdBottomSheet.hide();
                    }
                },
                targetEvent: $event
            });
        };

        $scope.init();
    };

}).call(this);

