// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name createController
 */


/* @ngInject */

(function() {
    module.exports = function($scope, promotionService) {

    };

}).call(this);


