// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name editController
 */


/* @ngInject */

(function() {
    module.exports = function($scope, $routeParams, $mdToast, $mdBottomSheet, $mdDialog, $location, subscriptionService, collectionService) {

        $scope.subscription = {};
        $scope.collections = [];
        $scope.loading = true;
        $scope.error = false;
        $scope.subscription_plan_types = [];

        $scope.init = function() {

            subscriptionService.getAllPlans()
                .success(function(res){
                    var arr = [];
                    for (var prop in res) {
                        arr.push(res[prop]);
                    }
                    $scope.subscription_plan_types = arr;
                })
                .error(function(){
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Ha ocurrido un error al cargar los planes de suscription. Intentalo nuevamente mas tarde.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                });

            if($routeParams.id) {
                subscriptionService.get($routeParams.id)
                    .success(function(res){
                        $scope.subscription = res.subscription;
                        $scope.subscription.expired_at = new Date($scope.subscription.expired_at);
                        $scope.subscription.created_at = new Date($scope.subscription.created_at);

                        collectionService.get($scope.subscription.owner.collections[0])
                            .success(function(res){
                                $scope.collections = res.collections;
                            });

                        $scope.loading = false;
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.loading = false;
                        $scope.error = true;
                    });

            }
        };

        $scope.save = function(redirect) {
            $scope.loading = true;
        };

        $scope.cancel = function($event) {
            $event.preventDefault();
            $location.path('/users/subscriptions');
        };

        $scope.getSubscriptionPlan = function (id) {
            for (var i = 0; i < $scope.subscription_plan_types.length; i++) {
                if ($scope.subscription_plan_types[i].id === id) {
                    return $scope.subscription_plan_types[i];
                }
            }
        };

        $scope.init();

    };

}).call(this);