// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name createController
 */


/* @ngInject */

(function() {
    module.exports = function($scope, $routeParams, $mdToast, $mdBottomSheet, $mdDialog, $location, userService, $timeout) {

        $scope.user = {};
        $scope.loading = true;
        $scope.error = false;
        $scope.isNewRow = false;

        $scope.init = function() {
            if($routeParams.id) {
                userService.get($routeParams.id)
                    .success(function(res){
                        $scope.user = res.user;
                        $scope.loading = false;
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.loading = false;
                        $scope.error = true;
                    });

            } else {
                $scope.loading = false;
                $scope.isNewRow = true;
            }
        };

        $scope.save = function(redirect) {
            $scope.loading = true;
            if($scope.isNewRow) {
                userService.create($scope.user)
                    .success(function (res) {
                        if (res.user) {
                            $mdToast.show(
                                $mdToast.simple()
                                    .content('El usuario se guardo exitosamente.')
                                    .position('top right')
                                    .hideDelay(3000)
                            );
                            $scope.loading = false;
                            if (redirect) {
                                $location.path('/users');
                            }
                        }
                    })
                    .error(function () {
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.loading = false;
                    });
            } else {
                userService.edit($scope.user)
                    .success(function (res) {
                        if (res.user) {
                            $mdToast.show(
                                $mdToast.simple()
                                    .content('El usuario se guardo exitosamente.')
                                    .position('top right')
                                    .hideDelay(3000)
                            );
                            $scope.loading = false;
                            if (redirect) {
                                $location.path('/users');
                            }
                        }
                    })
                    .error(function () {
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.loading = false;
                    });
            }
        };

        $scope.cancel = function($event) {
            $event.preventDefault();
            $location.path('/users');
        };

        $scope.init();

    };

}).call(this);

