// Generated by CoffeeScript 1.8.0

/**
 @author
 @description
 @name listController
 */


/* @ngInject */

(function() {
    module.exports = function($scope, $mdBottomSheet, $location, $mdToast, $mdDialog, userService) {
        $scope.users = [];

        $scope.init = function(){
            $scope.getAll();
        };

        $scope.getAll = function() {
            userService.getAll()
                .success(function(res){
                    $scope.users = res.users;
                })
                .error(function(){
                    $mdToast.show(
                        $mdToast.simple()
                            .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                            .position('top right')
                            .hideDelay(3000)
                    );
                });
        };

        $scope.showActions = function($event, user) {
            var selfScope = $scope;

            $mdBottomSheet.show({
                templateUrl: 'templates/users/bottom-sheet-action-list.html',
                controller: function($scope){
                    $scope.user = user;


                    $scope.edit = function () {
                        $location.path('/users/' + $scope.user._id);
                        $mdBottomSheet.hide();
                    };

                    $scope.trash = function() {
                        selfScope.delete($event, $scope.user);
                        $mdBottomSheet.hide();
                    };

                    $scope.activate = function() {
                        $scope.activePreviusValue = $scope.user.active;

                        userService.activate($scope.user)
                            .success(function(res){
                                var status = (res.user.active ? 'activado' : 'desactivado');
                                $mdToast.show(
                                    $mdToast.simple()
                                        .content('Se ha ' + status +  ' el usuario exitosamente.')
                                        .position('top right')
                                        .hideDelay(3000)
                                );
                            })
                            .error(function(res){
                                $mdToast.show(
                                    $mdToast.simple()
                                        .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                        .position('top right')
                                        .hideDelay(3000)
                                );
                                $scope.user.active = $scope.activePreviusValue;
                            });
                    };

                    $scope.setAsAdmin = function() {
                        $scope.adminPreviusValue = user.admin;

                        var title = 'Realmente deseas que ' + user.username + ' sea un usuario estándar?';
                        var msg = 'Ahora ' + user.username + ' es un usuario estándar.';

                        if($scope.isAdmin) {
                            title = 'Realmente deseas que ' + user.username + ' sea Administrador?';
                            msg = 'Ahora ' + user.username + ' es Administrador.';
                        }

                        var confirm = $mdDialog.confirm()
                            .title(title)
                            .content('Puedes cambiar esto en cualquier momento.')
                            .ariaLabel('Administrador')
                            .ok('Ok')
                            .cancel('Cancelar')
                            .targetEvent($event);
                        $mdDialog.show(confirm).then(function () {
                            user.admin = $scope.isAdmin;
                            userService.admin(user)
                                .success(function (res) {
                                    $mdToast.show(
                                        $mdToast.simple()
                                            .content(msg)
                                            .position('top right')
                                            .hideDelay(3000)
                                    );

                                    $mdBottomSheet.hide();
                                })
                                .error(function () {
                                    $scope.isAdmin = !$scope.isAdmin;
                                    user.admin = $scope.adminPreviusValue;
                                    $mdToast.show(
                                        $mdToast.simple()
                                            .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                            .position('top right')
                                            .hideDelay(3000)
                                    );
                                });
                        }, function () {
                            $scope.isAdmin = !$scope.isAdmin;
                            user.admin = $scope.adminPreviusValue;
                            $mdToast.show(
                                $mdToast.simple()
                                    .content('La acción ha sido cancelada.')
                                    .position('top right')
                                    .hideDelay(3000)
                            );
                        });
                    }
                },
                targetEvent: $event
            });
        };

        $scope.delete = function($event, user) {
            var confirm = $mdDialog.confirm()
                .title('Realmente deseas eliminar el usuario: ' + user.username + '?')
                .content('Esta acción no puede deshacerse.')
                .ariaLabel('Eliminar usuario')
                .ok('Eliminar')
                .cancel('Cancelar')
                .targetEvent($event);
            $mdDialog.show(confirm).then(function() {
                userService.delete(user)
                    .success(function(res){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Se ha eliminado el usuario exitosamente.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                        $scope.init();
                    })
                    .error(function(){
                        $mdToast.show(
                            $mdToast.simple()
                                .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                                .position('top right')
                                .hideDelay(3000)
                        );
                    });
            }, function() {
                $mdToast.show(
                    $mdToast.simple()
                        .content('La eliminacion ha sido cancelada.')
                        .position('top right')
                        .hideDelay(3000)
                );
            });
        };

        $scope.create = function (){
            $location.path('/users/create');
        };

        $scope.edit = function (user) {
            $location.path('/users/' + user._id);
        };

        $scope.init();
    };

}).call(this);

