// Generated by CoffeeScript 1.8.0

/**
@author
@description
@name user/loginController
 */


/* @ngInject */

(function() {
  module.exports = function($scope, authenticatorService, $mdToast, $location) {
    $scope.credentials = {
      username: '',
      password: ''
    };

    $scope.login = function(credentials){
      authenticatorService.authenticate(credentials)
          .success(function(res){
              if(res.session.token){
                  authenticatorService.setToken(res.session.token);
                  $location.path('/');
              } else {
                  $mdToast.show(
                      $mdToast.simple()
                          .content('Ha ocurrido un error intentalo nuevamente mas tarde.')
                          .position('top right')
                          .hideDelay(3000)
                  );
              }

          })
          .error(function(){
              $mdToast.show(
                  $mdToast.simple()
                      .content('Usuario o contraseña incorrectos, intentalo nuevamente mas tarde.')
                      .position('top right')
                      .hideDelay(3000)
              );
          });
    };
  };

}).call(this);
